version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      my-network: # Connect web service to the network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: partnervista
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - mysql-data:/var/lib/mysql
      - ./partnervista-db.sql:/docker-entrypoint-initdb.d/partnervista-db.sql
    ports:
      - "3306:3306"
    networks:
      my-network: # Connect mysql service to the network

networks:
  my-network:

volumes:
  mysql-data:
