# Use the official MySQL image as base image
FROM mysql:8

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=your_database_name
ENV MYSQL_USER=your_database_user
ENV MYSQL_PASSWORD=your_database_password

# Copy your SQL script to initialize the database
COPY your_data.sql /docker-entrypoint-initdb.d/

# Expose the port your MySQL database runs on
EXPOSE 3306
